services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  backend:
    build: ./backend

  mail-dev:
    image: maildev/maildev
    container_name: restaurant-mail-dev
    ports:
      - "1080:1080"
      - "1025:1025"

  gateway:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
